//
// Created by drep on 2022-04-01.
//

#ifndef STIRLING_GAME_DEMO_DEFAULT_CONFIG_H
#define STIRLING_GAME_DEMO_DEFAULT_CONFIG_H

#define DEFAULT_IP_VERSION "IPv4"
#endif //STIRLING_GAME_DEMO_DEFAULT_CONFIG_H
